apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: {{ .Release.Name | default "mycluster" }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ required "serverInstances is required" .Values.serverInstances }}
  router:
    instances: {{ required "routerInstances is required" .Values.routerInstances }}
  secretName: {{ .Release.Name }}-cluster-secret
  imagePullPolicy : {{ required "image.pullPolicy is required" .Values.image.pullPolicy }}
  baseServerId: {{ required "baseServerId is required" .Values.baseServerId }}
  version: {{ .Values.serverVersion | default .Chart.AppVersion }}
  serviceAccountName: {{ .Release.Name }}-sa

{{- if .Values.datadirVolumeClaimTemplate }}
  {{- with .Values.datadirVolumeClaimTemplate }}
  datadirVolumeClaimTemplate:
    {{- if .accessModes }}
    accessModes: [ "{{ .accessModes }}" ]
    {{- end }}
    {{- if .resources.requests.storage }}
    resources:
      requests:
        storage: "{{ .resources.requests.storage }}"
    {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.mycnf }}
  mycnf: |
{{ .Values.mycnf | indent 4}}
{{- end }}

{{- if .Values.initDB}}
  {{- if and (and .Values.initDB.dump .Values.initDB.dump.name) (and .Values.initDB.clone .Values.initDB.donorUrl) }}
    {{- fail "Dump and Clone are mutually exclusive" }}
  {{- end }}

  {{- if and .Values.initDB .Values.initDB.clone }}
    {{- with .Values.initDB.clone }}
  initDB:
    clone:
      donorUrl: {{ required "initDB.clone.donorUrl is required" .donorUrl }}
      rootUser: {{ .rootUser | default "root" }}
      credentials: {{ required "initDB.clone.credentials is required" .credentials }}
    {{- end }}
  {{- end }}

  {{- if and .Values.initDB .Values.initDB.dump }}
    {{- with .Values.initDB.dump }}
      {{- if and .name (or .ociObjectStorage .persistentVolumeClaim) }}
  initDB:
    dump:
        {{- if .name }}
      name: {{ .name }}
        {{- end }}
        {{- if .path }}
      path: {{ .path }}
        {{- end }}
      storage:
        {{- if .ociObjectStorage }}
        ociObjectStorage:
          prefix: {{ required "initDB.dump.ociObjectStorage.prefix is required" .ociObjectStorage.prefix }}
          bucketName: {{ required "initDB.dump.ociObjectStorage.bucketName is required" .ociObjectStorage.bucketName }}
          credentials: {{ required "initDB.dump.ociObjectStorage.credentials is required" .ociObjectStorage.credentials }}
        {{- end }}
        {{- if .persistentVolumeClaim }}
        persistentVolumeClaim:
          {{- toYaml .persistentVolumeClaim | nindent 10}}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.backupProfiles }}
  backupProfiles:
  {{- $isDumpInstance := false }}
  {{- $isSnapshot := false }}
  {{- range $_, $profile := .Values.backupProfiles }}
    {{- if $profile.name }}
  - name: {{ $profile.name -}}
      {{- $isDumpInstance = hasKey $profile "dumpInstance" }}
      {{- $isSnapshot = hasKey $profile "snapshot" }}
      {{- if or $isDumpInstance $isSnapshot }}
        {{- $backupProfile := ternary $profile.dumpInstance $profile.snapshot $isDumpInstance }}
        {{- if $isDumpInstance }}
    dumpInstance:
        {{- else if $isSnapshot }}
    snapshot:
        {{- else }}
          {{- fail "Impossible backup type" }}
        {{ end }}
        {{- if not (hasKey $backupProfile "storage") }}
          {{- fail "backup profile $profile.name has no storage section" }}
        {{- else if hasKey $backupProfile.storage "ociObjectStorage" }}
      storage:
        ociObjectStorage:
          prefix: {{ required "prefix is required" $backupProfile.storage.ociObjectStorage.prefix }}
          bucketName: {{ required "bucketName is required"  $backupProfile.storage.ociObjectStorage.bucketName }}
          credentials: {{ required "credentials is required"  $backupProfile.storage.ociObjectStorage.credentials }}
        {{- else if hasKey $backupProfile.storage "persistentVolumeClaim" }}
      storage:
        persistentVolumeClaim: {{ toYaml $backupProfile.storage.persistentVolumeClaim | nindent 12}}
        {{- else -}}
          {{- fail "dumpInstance backup profile $profile.name has empty storage section - neither ociObjectStorage nor persistentVolumeClaim defined" }}
        {{- end -}}
      {{- else }}
        {{- fail "One of dumpInstance or snapshot must be methods of a backupProfile" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.backupSchedules }}
  backupSchedules:
  {{- $isDumpInstance := false }}
  {{- $isSnapshot := false }}
  {{- range $_, $schedule := .Values.backupSchedules }}
  - name: {{ $schedule.name }}
    schedule: {{ quote $schedule.schedule }}
    deleteBackupData: {{ $schedule.deleteBackupData }}
    enabled: {{ $schedule.enabled }}
    {{- if hasKey $schedule "backupProfileName"  }}
    backupProfileName: {{  $schedule.backupProfileName }}
    {{- else if hasKey $schedule "backupProfile" }}
      {{- $isDumpInstance = hasKey $schedule.backupProfile "dumpInstance" }}
      {{- $isSnapshot = hasKey $schedule.backupProfile "snapshot" }}
      {{- if or $isDumpInstance $isSnapshot }}
        {{- $backupProfile := ternary $schedule.backupProfile.dumpInstance $schedule.backupProfile.snapshot $isDumpInstance }}
    backupProfile:
        {{- if $isDumpInstance }}
      dumpInstance:
        {{- else if $isSnapshot }}
      snapshot:
        {{- end }}
        {{- if not (hasKey $backupProfile "storage") }}
          {{- fail "schedule backup profile $schedule.name has no storage section" }}
        {{- else if hasKey $backupProfile.storage "ociObjectStorage" }}
        storage:
          ociObjectStorage:
            prefix: {{ required "prefix is required" $backupProfile.storage.ociObjectStorage.prefix }}
            bucketName: {{ required "bucketName is required"  $backupProfile.storage.ociObjectStorage.bucketName }}
            credentials: {{ required "credentials is required"  $backupProfile.storage.ociObjectStorage.credentials }}
        {{- else if hasKey $backupProfile.storage "persistentVolumeClaim" }}
        storage:
          persistentVolumeClaim: {{ toYaml $backupProfile.storage.persistentVolumeClaim | nindent 12}}
        {{- else -}}
          {{- fail "dumpInstance backup profile $profile.name has empty storage section - neither ociObjectStorage nor persistentVolumeClaim defined" }}
        {{- end -}}
      {{- else }}
         {{- fail "Impossible backup type for a schedule" }}
      {{- end }}

    {{- else }}
      {{- fail "Neither backupProfileName nor backupProfile provided for a schedule" }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if false }}
{{- end }}
