apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds
  instances: 3
  router:
    instances: 1
# An example how to use storage class with InnoDBCluster
  datadirVolumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
    storageClassName: local
